main: de.timesnake.basic.loungebridge.core.main.BasicLoungeBridge
version: 1.3.1
name: basic-lounge-bridge
author: Mn
database: true
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  stats_discard:
  coins_discard:

