main: de.timesnake.basic.loungebridge.core.main.BasicLoungeBridge
version: ${version}
name: basic-lounge-bridge
author: timesnake
database: true
depend: [ basic-bukkit ]
api-version: 1.21

commands:
  stats_discard:
  coins_discard:
  worldborder:
    aliases:
      - wb

